apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: wattanai-com-tls
spec:
  secretName: wattanai.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: wattanai.com
  dnsNames:
    - wattanai.com
    - www.wattanai.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - wattanai.com
          - www.wattanai.com