apiVersion: certmanager.k8s.is/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'peem16@hotmail.com'
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}